"""Snapshot installed locked packages and preserve their shipped notices.

Run only after reviewing a dependency change. This is inventory generation,
not a legal clearance or a license-compatibility decision.
"""
import hashlib
import html
import importlib.metadata as metadata
import json
from pathlib import Path
import re

ROOT=Path(__file__).resolve().parent.parent
LEGAL=ROOT/'legal'


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def generate():
    lock=(ROOT/'requirements.lock.txt').read_text(encoding='utf-8-sig')
    packages=[]
    assets=[]
    extra={'tokenizers':['upstream/tokenizers-v0.22.2-LICENSE.txt'],
           'flatbuffers':['upstream/flatbuffers-LICENSE.txt'],
           'rapidocr-onnxruntime':['upstream/RapidOCR-APACHE-2.0.txt','upstream/PaddleOCR-APACHE-2.0.txt']}
    for line in lock.splitlines():
        if not line.strip() or line.startswith('#'):
            continue
        name,version=line.split('==')
        d=metadata.distribution(name)
        assert d.version==version,(name,d.version,version)
        paths=[]
        for f in d.files or []:
            # Keep license text and attribution, not unrelated Python modules named licenses.
            base=Path(f).name.lower()
            if not (any(word in base for word in ('license','copying','notice','authors')) or '/licenses/' in str(f).replace('\\','/').lower() or 'build_licenses' in str(f).lower()):
                continue
            src=Path(d.locate_file(f))
            if not src.is_file() or src.suffix in ('.py','.pyc'):
                continue
            relative=Path('packages')/name/re.sub(r'[^a-zA-Z0-9._-]','_',str(f))
            target=LEGAL/relative;target.parent.mkdir(parents=True,exist_ok=True)
            # 按**字节**复制并统一成 LF：这些是第三方许可原文，本项目仓库统一用 LF。
            # 若直接用 shutil.copyfile，wheel 里的 CRLF 会被原样写进来，于是"重跑一次清单生成"
            # 就会在 git 里产生 40 多个纯换行差异（2026-09-20 实际发生过一次）。
            data=src.read_bytes().replace(b'\r\n',b'\n')
            same=target.is_file() and target.read_bytes()==data
            if not same:
                target.write_bytes(data)
            paths.append(relative.as_posix())
        paths.extend(extra.get(name.lower(),[]))
        assert paths, f'Missing license files: {name}'
        license_id=d.metadata.get('License-Expression') or d.metadata.get('License') or 'See bundled license'
        urls=d.metadata.get_all('Project-URL') or []
        packages.append({'name':name,'version':version,'declared_license':license_id,
                         'source':f'https://pypi.org/project/{name}/{version}/','project_urls':urls,
                         'notices':[{'path':p,'sha256':digest(LEGAL/p)} for p in paths]})
        if name.lower()=='rapidocr-onnxruntime':
            for f in d.files or []:
                if str(f).endswith('.onnx'):
                    assets.append({'path':str(f).replace('\\','/'),'location':'installed-package','package':name,
                                   'sha256':digest(Path(d.locate_file(f))),'license':'Apache-2.0',
                                   'source':'https://github.com/RapidAI/RapidOCR','upstream':'PaddleOCR / Baidu and respective rights holders'})
    for path in sorted((ROOT/'static/fonts').iterdir()):
        if path.is_file():
            assets.append({'path':path.relative_to(ROOT).as_posix(),'location':'project','sha256':digest(path),
                           'license':'OFL-1.1','source':'https://github.com/notofonts/noto-cjk/tree/main/Sans','modified':False})
    # 图标是**仓库里的成品资源**，底图由设计者用生图 AI 生成（不是本项目手绘的几何图形）。
    # 项目采用 PolyForm Noncommercial 1.0.0，不使用于商业目的，因此这里不再记"商用前需核实平台条款"
    # 这一待办项；若将来改用允许商用的许可证，需重新核实并改回这句。来历见 docs/ICON.md。
    # 记录哈希的作用是：谁把静态目录里的图标换成别的图，check_licenses.py 会立刻报"已审文件被改动"。
    for name in ('icon.png','icon-256.png'):
        path=ROOT/'static'/name
        assert path.is_file(), f'缺少图标资源 {name}：见 docs/ICON.md 的复现步骤'
        assets.append({'path':path.relative_to(ROOT).as_posix(),'location':'project','sha256':digest(path),
                       'license':'Generated artwork supplied by the project author; provenance in docs/ICON.md; not licensed with the code (see legal/BRAND.md); project use is noncommercial (PolyForm Noncommercial 1.0.0)','modified':True,
                       'source':'scripts/build_icon.py','upstream':'source image generated by the project author with an image AI; see docs/ICON.md'})
    result={'review_date':'2026-09-15','scope':'Locked Python packages, their bundled notices, bundled UI fonts and OCR model bytes; not a legal opinion. Project code license: PolyForm Noncommercial 1.0.0 (LICENSE/NOTICE); this inventory covers third-party components only.',
            'lock_sha256':digest(ROOT/'requirements.lock.txt'),'packages':packages,'assets':assets}
    # newline='\n'：Windows 上 write_text 默认写 CRLF，会让整份清单在 diff 里变成
    # "每一行都改了"，而本仓库的验收项包含 git diff --check（CRLF 会被判成行尾空白）。
    # 见仓库根的 .gitattributes。
    (LEGAL/'inventory.json').write_text(json.dumps(result,ensure_ascii=False,indent=2),encoding='utf-8',newline='\n')
    rows=[]
    for p in packages:
        links=' '.join(f'<a href="{html.escape(n["path"])}">声明 {i+1}</a>' for i,n in enumerate(p['notices']))
        rows.append(f'<tr><td>{html.escape(p["name"])}</td><td>{html.escape(p["version"])}</td><td>{html.escape(p["declared_license"])}</td><td>{links}</td></tr>')
    page='''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>许可证与资源来源</title><link rel="stylesheet" href="/static/style.css"><style>body{display:block;height:auto;max-width:1100px;padding:30px;margin:auto}table{border-collapse:collapse;width:100%;font-size:12px}td,th{padding:10px;border:1px solid #dce3d5;text-align:left;overflow-wrap:anywhere}a{color:#28654e}p{line-height:1.9}.table-scroll{overflow:auto}</style></head><body><h1>许可证与资源来源</h1><p>本项目代码采用 <strong>PolyForm Noncommercial 1.0.0</strong>：任何非商业目的都可以使用、修改与分发，商业用途需另行取得许可；按 OSI 定义这<strong>不是</strong>开源许可，而是"源码可用"。名称与图标不在代码许可证的授权范围内。详见仓库根的 <code>LICENSE</code>、<code>NOTICE</code> 与 <code>legal/BRAND.md</code>。</p><p>界面使用本地附带的 Noto Sans CJK SC（SIL OFL 1.1），保留原始字体与许可证。原文 PDF 的字体和文件字节不做修改。</p><p>第三方组件保留各自版权与许可证。<strong>它们各自的许可条款与本项目的许可证无关</strong>——宽松许可允许被纳入以其他条款发布的更大作品，因此不冲突；反过来，本项目的非商业限制也不改变第三方组件自身的授权。</p><p>第三方组件的授权状况与分发边界见 THIRD-PARTY.md。重要：Shapely 附带 GEOS（LGPL），OpenCV 附带 FFmpeg（LGPL），certifi 使用 MPL。分发时保留声明、源码获取说明及相应替换/修改权利；不要把虚拟环境直接封装成不可替换的单文件程序——那会让打包者成为这些组件的分发者，义务随之转移。</p><p><a href="THIRD-PARTY.md">第三方组件与资源（哪些随仓库分发、哪些由使用者安装）</a> · <a href="THIRD-PARTY.md">第三方组件与资源</a> · <a href="inventory.json">版本与资源哈希清单</a> · <a href="/static/fonts/OFL.txt">字体许可证</a></p><div class="table-scroll"><table><thead><tr><th>组件</th><th>版本</th><th>上游声明</th><th>原始许可证与版权声明</th></tr></thead><tbody>'''+''.join(rows)+'''</tbody></table></div><p>OCR 模型来源于 PaddleOCR，经 RapidOCR 转换为 ONNX；模型适用 Apache 2.0，且<strong>内置在 rapidocr-onnxruntime 依赖包中</strong>，由使用者安装该依赖时取得，本仓库不包含也不分发这些模型文件。服务平台名称仅用于识别可连接服务，不表示合作或背书。本清单不授予用户上传文献或自行配置模型的使用权。</p></body></html>'''
    (LEGAL/'NOTICE.html').write_text(page,encoding='utf-8')
    print(f'Inventory: {len(packages)} packages, {len(assets)} assets')


if __name__=='__main__':
    generate()
